### ISSUE TITLE
Install and run Hubs locally

### ISSUE THREAD

**Issue by yuriaru** [RutgersGRID/hubs#2]

**Comment by MuhammadUzairDocs** [comment]
when I run "npm start" I have an error "Error fetching Hubs Cloud config "unauthorized".

**Comment by MuhammadUzairDocs** [comment]
To quick start:
git clone https://github.com/mozilla/hubs.git
cd hubs
npm ci 
npm run dev 

- npm ci allows you to install exact dependencies, make sure you do this step after you cd into hubs
- npm run dev allows you to see the project on localhost port 8080 (https://localhost:8080)

**Comment by MuhammadUzairDocs** [comment]
Errors seen with npm run dev (windows)

- When trying to npm run dev on windows there is an error with webxr-polyfill
- webxr is a api for virtual reality

**Comment by yuriaru** [comment]
> To quick start: git clone https://github.com/mozilla/hubs.git cd hubs npm ci npm run dev
> 
> * npm ci allows you to install exact dependencies, make sure you do this step after you cd into hubs
> * npm run dev allows you to see the project on localhost port 8080 (https://localhost:8080)

I was able to execute the procedure and install hubs successfully.

**Comment by MuhammadUzairDocs** [comment]
When running npm run dev, there is a certificate warning, These warning behave differently on different softwares.

Windows:
Chrome behavior: There will be a certificate warning saying that site is not safe to enter. If you press advanced, there will be an option to continue to the site.

Mac OS:
Chrome behavior: Like the Windows version of Chrome there is a certificate warning saying the site is not safe to enter. But when you press advanced this time there will not be an option to continue onto the site. 
Firefox behavior: After you get an error stating the site is not safe to enter. You are able to click advanced options and continue onto the site.
