### ISSUE TITLE
Catchup Meeting (11-02-21)

### ISSUE THREAD

**Issue by yuriaru** [RutgersGRID/hubs#5]

**Comment by MuhammadUzairDocs** [comment]
1. Find out what default.env 
2. Find out what each entry in file does
3. Figure out the values and see if they can take our instance
4. kill the instance and install the new settings 
5. execute and see if the local host changes

**Comment by MuhammadUzairDocs** [comment]
Screenshot running documentations

**Comment by MuhammadUzairDocs** [comment]
Try to contact the hubs server while making changes to local host, if that concept works you should be able to communicate with Rutgers Grid servers and makes changes to local host that will be reflected not the page
